@uri=http://localhost:3000/api/v1
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzkwYjc3MzEyOWI3MzllYWIyMzk0MmMiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzM3NTM3Mzk1LCJleHAiOjE3Mzc3MTAxOTV9.ywXzGB7Qf2py2dBb0YwkMBGnRPYotNSRX7UCUX2gsNM

###
POST {{uri}}/user/signup
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "12345"
}

### 
POST {{uri}}/user/login
authorization: Bearer {{accessToken}}
