@uri=http://localhost:3000/api/v1
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzkwYjc3MzEyOWI3MzllYWIyMzk0MmMiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzM3NTM3Mzk1LCJleHAiOjE3Mzc3MTAxOTV9.ywXzGB7Qf2py2dBb0YwkMBGnRPYotNSRX7UCUX2gsNM
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzkyMTM0ODg2MzIzYjYzNzgyMTI3NTciLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzM3NjI3MDcxLCJleHAiOjE3MzgyMzE4NzF9.LHVR-r5p51tcvX1nP_cUCm6Ouos-78dT2ansg-NHxoY
@apiKey=
### user signup
POST {{uri}}/user/signup
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "12345"
}

### user login
POST {{uri}}/user/login
x-refresh-token: {{refreshToken}}
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "12345"
}

### user refresh token
POST {{uri}}/user/refresh-token
x-refresh-token: {{refreshToken}}
Content-Type: application/json

{
    "userId": "6792134886323b6378212757"
}

### user logout
POST {{uri}}/user/logout
