@uri=http://localhost:3000/api/v1
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzkwYWY5Y2YwMmM5Y2JmNjdmNzhlZWYiLCJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiaWF0IjoxNzM3NTM1Mzg4LCJleHAiOjE3Mzc3MDgxODh9.VYh3TsPqYrbjIBfC-d4PP69Dgx5jWH45dLdJN1bssP4

###
POST {{uri}}/user/signup
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@gmail.com",
    "password": "12345"
}

### 
POST {{uri}}/user/login
authorization: Bearer {{accessToken}}
